updates

diff --git a/workflow/aref/snakefile b/workflow/aref/snakefile
--- a/workflow/aref/snakefile
+++ b/workflow/aref/snakefile
@@ -217,23 +217,41 @@ rule dorado:
         slurm_partition="gpu-he",
         mem_mb = 128000,
         runtime = 5760,
-        slurm_extra="'--gres=gpu:2 --constraint=a6000|h100|a100|l40s|b200'"
+        slurm_extra="'--gres=gpu:l40s:2' '--exclude=gpu2708'"
     shell:
         """
 mkdir -p $(dirname {output.calls})
 mod_string=$(echo {wildcards.modifications_string} | tr "-" ",")
 
-dorado \
-basecaller \
-{wildcards.type},$mod_string \
-{params.input_dir} \
---recursive \
---modified-bases-threshold 0 \
---trim all \
---verbose \
---reference {params.reference} \
---mm2-opts "-x map-ont -Y" > {output.calls}.unfinished
-mv {output.calls}.unfinished {output.calls}
+if [[ -f {output.calls}.unfinished ]]; then
+    echo "Resuming from existing unfinished bam"
+    dorado \
+    basecaller \
+    {wildcards.type},$mod_string \
+    {params.input_dir} \
+    --recursive \
+    --modified-bases-threshold 0 \
+    --trim all \
+    --verbose \
+    --reference {params.reference} \
+    --mm2-opts "-x map-ont -Y" \
+    --resume-from {output.calls}.unfinished > {output.calls}.resumed \
+    || {{ echo "Resume failed, removing corrupt file"; rm -f {output.calls}.unfinished {output.calls}.resumed; exit 1; }}
+    mv {output.calls}.resumed {output.calls}
+else
+    echo "Starting new basecalling run"
+    dorado \
+    basecaller \
+    {wildcards.type},$mod_string \
+    {params.input_dir} \
+    --recursive \
+    --modified-bases-threshold 0 \
+    --trim all \
+    --verbose \
+    --reference {params.reference} \
+    --mm2-opts "-x map-ont -Y" > {output.calls}.unfinished
+    mv {output.calls}.unfinished {output.calls}
+fi
         """
 
 rule dorado_unmappedbam:
@@ -268,53 +286,7 @@ basecaller \
 --verbose > {output.calls}.unfinished
 mv {output.calls}.unfinished {output.calls}
         """
-
-
-rule dorado_resume:
-    input:
-        unfinished = "aref/intermediates/{sample}/alignments/{rate}/{sample}.{type}.{modifications_string}.bam.unfinished"
-    output:
-        calls = "aref/intermediates/{sample}/alignments/{rate}/{sample}.{type}.{modifications_string}.finished.bam"
-    wildcard_constraints:
-        sample="[0-9A-Za-z_]+",
-        type = "[0-9A-Za-z]+",
-        rate = "[0-9A-Za-z]+",
-        modifications_string = "[0-9A-Za-z_-]+"
-    benchmark:
-        "aref/benchmarks/dorado_resume/{rate}.{sample}.{type}.{modifications_string}.tsv"
-    params:
-        reference = config["aref"]["update_ref_with_tldr"]["tldr_input_bam_ref"],
-        input_dir = lambda wildcards: sample_table.loc[sample_table["sample_name"] == wildcards.sample, "nanopore_rawdata_dir"].iloc[0]
-    container:
-        dorado_container
-    resources:
-        cpus_per_task =12,
-        slurm_partition="gpu-he",
-        mem_mb = 128000,
-        runtime = 5760,
-        slurm_extra="'--gres=gpu:2'"
-    shell:
-        """
-mkdir -p $(dirname {output.calls})
-mod_string=$(echo {wildcards.modifications_string} | tr "-" ",")
-
-dorado \
-basecaller \
-{wildcards.type},$mod_string \
-{params.input_dir} \
---resume-from {input.unfinished} \
---recursive \
---verbose \
---reference {params.reference} \
---mm2-opts "-x map-ont" > {output.calls}.temp.bam
-mv {output.calls}.temp.bam {output.calls}
-        """
         
-rule call_dorado_resume:
-    input:
-        expand("aref/intermediates/{sample}/alignments/{rate}/{sample}.{type}.{modifications_string}.bam.finished", sample = config["aref"]["samples"], rate = config["aref"]["rate"], type = config["aref"]["type"], modifications_string = config["aref"]["modification_string"])
-
-
 rule dorado_seqsummary:
     input:
         sortedbam = expand("aref/intermediates/{{sample}}/alignments/{rate}/{{sample}}.{type}.{modification_string}.sorted.bam", rate = config["aref"]["rate"], type = config["aref"]["type"], modification_string = config["aref"]["modification_string"]),
@@ -607,7 +579,8 @@ rule tldr_per_sample:
     resources:
         cpus_per_task = 24,
         mem_mb = 300000,
-        runtime = 3000
+        runtime = 3000,
+        tldr_concurrent = 1
     container: None
     conda:
         "tldr"
@@ -644,6 +617,7 @@ tldr -b {input.bam} \
 
 fi
 
+rm -rf $(dirname {output.tldr})
 mkdir -p $(dirname {output.tldr})
 mv {wildcards.sample}.table.txt {output.tldr}
 mv {wildcards.sample} $(dirname {output.tldr})/
